
import React from 'react';

const commonStyles = {
  h3: "text-xl font-bold text-brand-text-primary mt-6 mb-2",
  p: "text-brand-text-secondary mb-4",
  ul: "list-disc list-inside text-brand-text-secondary space-y-2 mb-4",
  li: "pl-2",
  strong: "font-bold text-brand-text-primary",
}

export const TermsAndConditions: React.FC = () => (
    <div className="prose prose-sm max-w-none text-brand-text-secondary">
        <p className={commonStyles.p}>Last updated: {new Date().toLocaleDateString()}</p>
        
        <h3 className={commonStyles.h3}>1. Acceptance of Terms</h3>
        <p className={commonStyles.p}>By creating an account and using the WinkDrops application ("Service"), you agree to be bound by these Terms and Conditions ("Terms"). If you disagree with any part of the terms, then you may not access the Service. Your use of the Service is expressly conditioned upon your assent to all of the terms and conditions of this agreement.</p>
        
        <h3 className={commonStyles.h3}>2. Service Description</h3>
        <p className={commonStyles.p}>WinkDrops allows users to send anonymous messages of concern ("Winks") containing AI-generated content. The service is intended as a tool to encourage supportive communication.</p>
        
        <h3 className={commonStyles.h3}>3. NO MEDICAL ADVICE & EMERGENCY USE DISCLAIMER</h3>
        <p className={commonStyles.p}>
            The content, insights, and resources provided by WinkDrops, whether generated by AI or otherwise, <span className={commonStyles.strong}>DO NOT CONSTITUTE MEDICAL ADVICE, diagnosis, or treatment.</span> The Service is for informational and educational purposes only.
        </p>
        <p className={commonStyles.p}>
            <span className={commonStyles.strong}>WinkDrops is NOT a crisis intervention service and must not be used for emergencies.</span> If you or someone you know is in crisis, in immediate danger, or experiencing a medical emergency, please contact a crisis hotline (call or text 988 in the US/Canada) or your local emergency services (911) immediately.
        </p>
        <p className={commonStyles.p}>
            Never disregard professional medical advice or delay in seeking it because of something you have read on or received from WinkDrops. You assume full risk and responsibility for your use of information obtained from or through the Service.
        </p>
        
        <h3 className={commonStyles.h3}>4. Limitation of Liability</h3>
        <p className={commonStyles.p}>
            THE SERVICE IS PROVIDED ON AN <span className={commonStyles.strong}>"AS IS"</span> AND <span className={commonStyles.strong}>"AS AVAILABLE"</span> BASIS. WINKDROPS, ITS CREATORS, AFFILIATES, EMPLOYEES, AND AGENTS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        </p>
        <p className={commonStyles.p}>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL WINKDROPS OR ITS AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES—INCLUDING BUT NOT LIMITED TO, DAMAGES FOR EMOTIONAL DISTRESS, LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES—RESULTING FROM (I) YOUR USE OF, OR INABILITY TO USE, THE SERVICE; (II) THE CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; OR (III) ANY OTHER MATTER RELATING TO THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, EVEN IF WINKDROPS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p className={commonStyles.p}>
            <span className={commonStyles.strong}>YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY DISPUTE WITH WINKDROPS IS TO DISCONTINUE YOUR USE OF THE SERVICE.</span>
        </p>

        <h3 className={commonStyles.h3}>5. Indemnification</h3>
        <p className={commonStyles.p}>
            You agree to defend, indemnify, and hold harmless WinkDrops, its creators, affiliates, and their respective officers, directors, employees, and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Service; (ii) your violation of any term of these Terms; or (iii) your violation of any third-party right, including without limitation any copyright, property, or privacy right.
        </p>

        <h3 className={commonStyles.h3}>6. User Conduct & Responsibility</h3>
        <p className={commonStyles.p}>You are solely responsible for your interactions with other users and for any content you generate. You agree not to use WinkDrops for any unlawful, harmful, threatening, abusive, harassing, defamatory, or malicious purpose. We are not responsible for the conduct of any user of the Service.
        </p>
    </div>
);

export const PrivacyPolicy: React.FC = () => (
    <div className="prose prose-sm max-w-none text-brand-text-secondary">
        <p className={commonStyles.p}>Last updated: {new Date().toLocaleDateString()}</p>
        
        <h3 className={commonStyles.h3}>1. Information Collection and Use</h3>
        <p className={commonStyles.p}>WinkDrops is designed with your privacy in mind. When you create an account, we collect your name and email address for authentication purposes. All other data you generate, including contacts, inbox, and outbox messages, is stored locally on your device or within your secured account data. We do not sell your personal data.</p>
        
        <h3 className={commonStyles.h3}>2. Anonymity</h3>
        <p className={commonStyles.p}>The core feature of WinkDrops is anonymity for the sender of a "Wink." We have no technical means to reveal a sender's identity to a recipient. We encourage users to be mindful not to include any self-identifying details in custom observations to maintain their own privacy.</p>
        
        <h3 className={commonStyles.h3}>3. Third-Party AI Services</h3>
        <p className={commonStyles.p}>To generate content, we send the non-personal, observational data you select to third-party AI models (such as Google's Gemini API). This data is not linked to you or the recipient in any personally identifiable way. We recommend reviewing the privacy policies of these third-party services for information on how they handle data.</p>

        <h3 className={commonStyles.h3}>4. Geolocation Data</h3>
        <p className={commonStyles.p}>If you choose to use features that find local resources, we will request one-time access to your browser's geolocation data. This information is sent to the AI service to perform the search and is not stored or tracked by WinkDrops after the search is complete.</p>
        
        <h3 className={commonStyles.h3}>5. Data Security</h3>
        <p className={commonStyles.p}>We use industry-standard security measures to protect your account information. However, you are also responsible for maintaining the security of your account by using a strong password and enabling multi-factor authentication where available.</p>
    </div>
);
